Change gcovr output to allow for Multiple Output Formats
bilke/cmake-modules pull request #67
Opened 2022-02-22 17:19 UTC by FranzBranntvino

Change gcovr output from -o <filename> for --xml <filename> and --html <filename> output respectively.
This will allow for Multiple Output Formats at teh soame time by making use of GCOVR_ADDITIONAL_ARGS, e.g. GCOVR_ADDITIONAL_ARGS "--txt".

2022-02-28 12:43 UTC, bilke requested changes

2022-02-28 12:43 UTC, bilke commented on CodeCoverage.cmake
> +#       This will allow for Multiple Output Formats at teh soame time by making use of GCOVR_ADDITIONAL_ARGS, e.g. GCOVR_ADDITIONAL_ARGS "--txt".
Thanks for this contribution! Please fix the spelling on this line "the same time" and I will merge it.

2022-03-01 09:36 UTC, bilke approved these changes

2022-03-01 09:36 UTC, merged

2022-03-14 14:50 UTC, pvheiningen commented
Quick heads-up that this change only works from gcovr version 4.0 (when the --html [OUTPUT] option was added)

See:
https://gcovr.com/en/stable/changelog.html#june-2018

```
Format flag parameters like [--xml](https://gcovr.com/en/stable/guide.html#cmdoption-gcovr-x) or [--html](https://gcovr.com/en/stable/guide.html#cmdoption-gcovr-html) now take an optional output file name.
```